### ISSUE TITLE
[TD-86] Implement a per-request processing timeout

### ISSUE THREAD

**Issue by taskwarrior** [GothenburgBitFactory/taskserver#86]
_Paul Beckingham on 2014-12-29T19:00:05Z says:_ 

 Prevent single sync requests from taking too long by providing a configurable timeout mechanism.

**Comment by taskwarrior** [comment]
Migrated metadata:
```
Created: 2014-12-29T19:00:05Z
Modified: 2015-02-28T18:26:56Z
```

**Comment by madduck** [comment]
Please up the priority on this one. I am using the inofficial TaskWarrior app on Android (the one that wraps `task` in a nice GUI), and it happens every few days that the connection hangs, e.g. because I switch networks or lose connectivity. As a consequence, the server process actually waits indefinitely, making sync impossible for all users.

Of course, it'd be even better to be able to handle multiple requests, as per #72 and #85, but killing a connection after a number of seconds of inactivity would already go a long way.

**Comment by lauft** [comment]
> [!IMPORTANT]
> Taskserver is only compatible with Taskwarrior 2.x, and is no longer actively developed.
> See `man task-sync` for task synchronization with Taskwarrior 3
